#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
[package]
name = "pravega_protocol_adapter"
version = "0.1.0"
authors = ["Claudio Fahey <claudio.fahey@dell.com>"]
repository = "https://github.com/pravega/gstreamer-pravega"
license = "Apache-2.0"
description = "Pravega Protocol Adapter for NVIDIA DeepStream"
edition = "2018"

[dependencies]
anyhow = "1"
pravega-client = { path = "../../pravega-client-rust" }
pravega-client-config = { path = "../../pravega-client-rust/config" }
pravega-client-shared = { path = "../../pravega-client-rust/shared" }
tracing = "0.1"
tracing-subscriber = "0.2"
tokio = { version = "1.1", features = ["full"] }
url = "2"

[lib]
name = "nvds_pravega_proto"
crate-type = ["cdylib"]
path = "src/lib.rs"
